# Generated by Django 4.2.7 on 2023-11-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название статьи')),
                ('body', models.TextField(verbose_name='содержание статьи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата и время написания')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
