# Generated by Django 4.2.7 on 2023-11-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
